name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test backend imports
      run: |
        python -c "import app; print('Backend imports successfully')"
    
    - name: Check if model files exist
      run: |
        if [ ! -f "fraud_model.pkl" ]; then
          echo "Error: fraud_model.pkl not found"
          exit 1
        fi
        if [ ! -f "scaler.pkl" ]; then
          echo "Error: scaler.pkl not found"
          exit 1
        fi
        echo "Model files found successfully"

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: fraud-finder-web-1/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: fraud-finder-web-1
      run: npm ci
    
    - name: Build frontend
      working-directory: fraud-finder-web-1
      run: npm run build
    
    - name: Test frontend build
      working-directory: fraud-finder-web-1
      run: |
        if [ ! -d "dist" ]; then
          echo "Error: dist directory not found"
          exit 1
        fi
        echo "Frontend build successful"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: fraud-finder-web-1/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: fraud-finder-web-1
      run: npm ci
    
    - name: Run ESLint
      working-directory: fraud-finder-web-1
      run: npm run lint 